apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: capstone
  labels:
    app: backend
    env: dev
    project: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: dev
      project: capstone
  template:
    metadata:
      labels:
        app: backend
        env: dev
        project: capstone
    spec:
      containers:
        - name: backend
          image: daneshsd2002/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
