apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: capstone
  labels:
    app: frontend
    env: dev
    project: capstone
spec:
  selector:
    app: frontend
    env: dev
    project: capstone
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
